#!/bin/bash
files="$(yad --width=600 --height=400 --file-selection --title="Choose Markdowns" \
--text="Enter Markdown File" --filename="/home/robert/Dropbox/MD")"

[[ -z $files  ]] && exit 1

template="$(yad --file-selection --title="Choose Template" \
--text="Enter Markdown File" --filename="/home/robert/Dropbox/MD")"

pandoc --reference-odt="$template" -f markdown "$files" -o "`echo $files | sed 's/\(.*\.\)md/\1odt/'`"
