#!/bin/bash
files="$(yad --width=600 --height=400 --file-selection --directory --title="Choose html Directory" --text="Enter html Directory" --filename="$HOME/Dropbox/Notes")"

[[ -z $files  ]] && exit 1

find "$files" -type f -name '*.html' -exec pandoc -f html --wrap=none {} -o {}.md \;
rename .html '' "$files"/*.md
rm "$files"/*.html

